### ISSUE TITLE
Request: ExtendedLeavesBlock should extend LeavesBlock

### ISSUE THREAD

**Issue by Fourmisain** [TerraformersMC/Terraform#26]
## Description

Hi, I'm a maintainer of the [Falling Leaves mod](https://www.curseforge.com/minecraft/mc-mods/falling-leaves-fabric) that lets leaves fall from any block that is an instance of `LeavesBlock`.

Today I noticed that Terrestria's Redwood Leaves did not drop leaves when they should (with the settings I used at least).
Digging into it I found that they are instances of `TerrestriaOptiLeavesBlock`, which extends from Terraform's `ExtendedLeavesBlock` which directly extends from `Block`, which explains why no leaves would fall from it.

`TerraformLeavesBlock` and `TransparentLeavesBlock` do extend from `LeavesBlock`, so I'm wondering if there's a technical reason why `ExtendedLeavesBlock` can't too?

## Related Issues

https://github.com/RandomMcSomethin/fallingleaves/issues/17

**Comment by NeusFear** [comment]
The reason is purley compatibility related, as ironic as that sounds from someone requesting compatibility. Our leaves blocks require a diffreent distance property to that of vanilla so we can make them span further and this approach of implementing our own keeps us from having to overwrite anything vanilla has implemented. It's caused issues before because mod authors like yourself (not a jab) are not testing for the leaves tag, but instead the block's instance. 

Your solution here would be to add compabibility by testing for our parent class (not reccomended), or by just using the leaves tag (very reccomended).

Hope this helps!

**Comment by Fourmisain** [comment]
I understand, I just found out about the leaves tag as well, so we'll try to just use that.

Thanks for the quick answer!

**Comment by coderbot16** [comment]
To clarify: since some mods assume that any block that extends LeavesBlock has the DISTANCE_1_7 property, but our leaves only have the DISTANCE_1_14 property, they could crash when trying to find the DISTANCE_1_7 property.

I decided that it was slightly more preferable for mods that check for LeavesBlock to just silently fail instead of potentially crashing in the presence of Terrestria.

And yeah, using the leaves tag is probably the best approach here.

**Comment by Fourmisain** [comment]
Thanks for the clarification, that does make sense.

I did just implement using the `LEAVES` tag and was trying to use `Block.randomDisplayTick`, wondering why it wouldn't be called on any Terraform leaf blocks until I realized `ExtendedLeavesBlock` actually redirects the call to oak leaves:
https://github.com/TerraformersMC/Terraform/blob/e01e308cfd786ed502dec146892dbebca9cc3a61/terraform-wood-api-v1/src/main/java/com/terraformersmc/terraform/leaves/block/ExtendedLeavesBlock.java#L101-L105

That actually makes it super easy for me (it's literally a 1 line code change now) and I don't need to worry about possible performance issues of hooking into `Block.randomDisplayTick`.

Random trivia:
Did you know that Minecraft calls `randomDisplayTick` 666 times on random blocks in a 16 block radius, followed by another 666 times on blocks in a 32 block radius?
