### ISSUE TITLE
Remove MapColor from StrippableLogBlock constructor

### ISSUE THREAD

**Issue by ghost** [TerraformersMC/Terraform#40]
Next major version update of the wood api can we remove `MapColor` from the `StrippableLogBlock` constructor.

**Comment by gniftygnome** [comment]
A while back I deprecated all of `StrippableLogBlock` because it's better to use the FAPI registry.  The replacement helper methods in `PillarLogHelper` do expect either one or two `MapColor` arguments, but aside from setting a map color, I do not know why one would use the helpers anyway.  I think this issue can be resolved as either done or wont depending on the resolver's personal preferences.

**Comment by gniftygnome** [comment]
`StrippableLogBlock` was removed in v9 (https://github.com/TerraformersMC/Terraform/commit/2b5cacf0388ef9b29c261055429c1687c461c859) so I'm going to lay this issue to rest.
